#%RAML 1.0
---

title: Marriage Allowance Test Support
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/marriage-allowance-test-support:
  /sa:
    /{utr}:
      uriParameters:
        utr:
          description: The 10 digit self assessment UTR for the individual.
          type: string
          example: "2234567890"
      /status:
        /{taxYear}:
          uriParameters:
            taxYear:
              description: The tax year for which the Marriage Allowance status is being created.
              type: types.taxYear
          post:
            displayName: Create Marriage Allowance status test data
            description: |
                Lets you create Marriage Allowance status test data.

                Supports the [Get Marriage Allowance status resource method](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance#_get-marriage-allowance-status_get_accordion) on the Marriage Allowance API.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
            body:
              application/json:
                example: !include examples/create-marriage-allowance-status.json
                type: !include schemas/create-marriage-allowance-status.json
            responses:
              201:
                body:
                  application/json:
                    example: !include examples/create-marriage-allowance-status.json
                    type: !include schemas/create-marriage-allowance-status.json


  /nino:
    /{nino}:
      uriParameters:
        nino:
          description: Partner’s (potential recipient’s) National Insurance number. This must match the National Insurance number of an individual created using the [Create Test User API](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user).
          type: string
          example: "AA000003D"
      /eligibility:
        /{taxYear}:
          uriParameters:
            taxYear:
              description: The tax year for which the Marriage Allowance eligibility is being created.
              type: types.taxYear
          post:
            displayName: Create Marriage Allowance eligibility test data
            description: |
                Lets you create Marriage Allowance eligibility test data.

                Supports the [Check Marriage Allowance eligibility resource method](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance#_check-marriage-allowance-eligibility_get_accordion) on the Marriage Allowance API.
            is: [headers.acceptHeader]
            securedBy: [ sec.x-application ]
            body:
              application/json:
                example: !include examples/create-marriage-allowance-eligibility.json
                type: !include schemas/create-marriage-allowance-eligibility.json
            responses:
              201:
                body:
                  application/json:
                    example: !include examples/create-marriage-allowance-eligibility.json
                    type: !include schemas/create-marriage-allowance-eligibility.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: No test individual exists with the specified National Insurance number
                        value:
                          code: TEST_USER_NOT_FOUND

