openapi: 3.0.0
info:
  title: Marriage Allowance Test Support
  contact: {}
  version: '1.0'
servers:
- url: https://api.service.hmrc.gov.uk/
  variables: {}
paths:
  /marriage-allowance-test-support/sa/{utr}/status/{taxYear}:
    post:
      tags:
      - marriage-allowance-test-support
      summary: Create Marriage Allowance status test data
      description: >
        Lets you create Marriage Allowance status test data.


        Supports the [Get Marriage Allowance status resource method](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance#_get-marriage-allowance-status_get_accordion) on the Marriage Allowance API.
      operationId: CreateMarriageAllowancestatustestdata
      parameters:
      - name: utr
        in: path
        description: The 10 digit self assessment UTR for the individual.
        required: true
        style: simple
        schema:
          type: string
          example: '2234567890'
      - name: taxYear
        in: path
        description: The tax year for which the Marriage Allowance status is being created.
        required: true
        style: simple
        schema:
          pattern: ^[0-9]{4}-[0-9]{2}$
          type: string
          example: 2016-17
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/MarriageAllowanceTestSupportSaStatusrequest'
              - example:
                  status: Recipient
                  deceased: false
            example:
              status: Recipient
              deceased: false
        required: true
      responses:
        '201':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/MarriageAllowanceTestSupportSaStatusresponse'
                - example:
                    status: Recipient
                    deceased: false
              example:
                status: Recipient
                deceased: false
      deprecated: false
      security:
        - application-restricted: []
  /marriage-allowance-test-support/nino/{nino}/eligibility/{taxYear}:
    post:
      tags:
      - marriage-allowance-test-support
      summary: Create Marriage Allowance eligibility test data
      description: >
        Lets you create Marriage Allowance eligibility test data.


        Supports the [Check Marriage Allowance eligibility resource method](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/marriage-allowance#_check-marriage-allowance-eligibility_get_accordion) on the Marriage Allowance API.
      operationId: CreateMarriageAllowanceeligibilitytestdata
      parameters:
      - name: nino
        in: path
        description: Partner’s (potential recipient’s) National Insurance number. This must match the National Insurance number of an individual created using the [Create Test User API](https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user).
        required: true
        style: simple
        schema:
          type: string
          example: AA000003D
      - name: taxYear
        in: path
        description: The tax year for which the Marriage Allowance eligibility is being created.
        required: true
        style: simple
        schema:
          pattern: ^[0-9]{4}-[0-9]{2}$
          type: string
          example: 2016-17
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/MarriageAllowanceTestSupportNinoEligibilityrequest'
              - example:
                  eligible: true
            example:
              eligible: true
        required: true
      responses:
        '201':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/MarriageAllowanceTestSupportNinoEligibilityresponse'
                - example:
                    eligible: true
              example:
                eligible: true
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: TEST_USER_NOT_FOUND
              examples:
                invalidNino:
                  description: No test individual exists with the specified National Insurance number
                  value:
                    code: TEST_USER_NOT_FOUND
      deprecated: false
      security:
        - application-restricted: []
components:
  securitySchemes:
    application-restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [application-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token in the Authorization header.
      flows:
        clientCredentials:
          tokenUrl: https://test-api.service.hmrc.gov.uk/oauth/token
          scopes: {}
  schemas:
    errorResponse:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
    MarriageAllowanceTestSupportNinoEligibilityrequest:
      title: MarriageAllowanceTestSupportNinoEligibilityrequest
      required:
      - eligible
      type: object
      properties:
        eligible:
          type: boolean
          description: Whether the taxpayer's partner is eligible to become a recipient of Marriage Allowance
      description: Create Marriage Allowance eligibility test data payload
    MarriageAllowanceTestSupportNinoEligibilityresponse:
      title: MarriageAllowanceTestSupportNinoEligibilityresponse
      required:
      - eligible
      type: object
      properties:
        eligible:
          type: boolean
          description: Whether the taxpayer's partner is eligible to become a recipient of Marriage Allowance
      description: Create Marriage Allowance eligibility test data payload
    MarriageAllowanceTestSupportSaStatusrequest:
      title: MarriageAllowanceTestSupportSaStatusrequest
      required:
      - status
      - deceased
      type: object
      properties:
        status:
          oneOf:
          - $ref: '#/components/schemas/Status'
          - $ref: '#/components/schemas/Status1'
          - $ref: '#/components/schemas/Status2'
          description: The role of the taxpayer as recipient or transferor
        deceased:
          type: boolean
          description: Whether the taxpayer is deceased or not
      description: Create Marriage Allowance status test data payload
    MarriageAllowanceTestSupportSaStatusresponse:
      title: MarriageAllowanceTestSupportSaStatusresponse
      required:
      - status
      - deceased
      type: object
      properties:
        status:
          oneOf:
          - $ref: '#/components/schemas/Status'
          - $ref: '#/components/schemas/Status1'
          - $ref: '#/components/schemas/Status2'
          description: The role of the taxpayer as recipient or transferor
        deceased:
          type: boolean
          description: Whether the taxpayer is deceased or not
      description: Create Marriage Allowance status test data payload
    Status:
      title: Status
      enum:
      - Transferor
      type: string
      description: The taxpayer has transferred personal allowance in the given tax year
    Status1:
      title: Status1
      enum:
      - Recipient
      type: string
      description: The taxpayer has received personal allowance in the given tax year
    Status2:
      title: Status2
      enum:
      - None
      type: string
      description: The taxpayer has not transferred or received personal allowance in the given tax year
tags:
- name: marriage-allowance-test-support
  description: ''
